[package]
name = "relay-server"
version = "0.1.0"
edition = "2024"

[dependencies]
renet = "1.2.0"
renet_netcode = "1.2.0"
tokio = { version = "1", features = ["full"] }
warp = { version = "0.4.2", features = ["server"] }
serde_json = "1.0.145"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
thiserror = "2.0.17"
log = "0.4.28"
