udp_bind_address = "0.0.0.0:8080"
app_whitelist = []
allowed_versions = ["1.1.0_beta"]
relay_id = "L"
pocketbase_url = "http://127.0.0.1:8090"
pocketbase_email = "relay-server@nodetunnel.io"
pocketbase_password = "M8Ebd3ft9nDsv9"