# fly.toml app configuration file generated for relay-server on 2025-11-08T00:31:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'relay-server'
primary_region = 'iad'

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 0

[[services]]
  internal_port = 8080
  protocol = "udp"

  [[services.ports]]
    port = 8080

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
